### ISSUE TITLE
Add support to all intellij products

### ISSUE THREAD

**Issue by jclx** [dubreuia/intellij-plugin-save-actions#18] opened 2015-08-28 16:51 UTC
If you add 
    <depends>com.intellij.modules.lang</depends>

to the plugin.xml it will on all intellij products like webstorm.

Great plugin btw.

**Comment by dubreuia** [comment] 2015-09-01 11:41
Thanks, I'll add that, but I'll need to test it in all intellij products.

**Comment by dubreuia** [comment] 2015-12-10 15:00
From twitter: "Hi there, I just installed Save Actions on phpstorm 9.0.2 but cannot find the settings as described in the documentation."

**Comment by dubreuia** [comment] 2016-03-02 15:08
Lots of demand for this:

- PyCharm (https://github.com/dubreuia/intellij-plugin-save-actions/pull/22)
- Android Studio #31 
- PHPStorm #32

**Comment by XXChester** [comment] 2016-05-10 19:40
Guess the php webstorm support never made it in? Was really excited when I found this plugin and it installed fine, just cannot find the settings anywhere.

**Comment by dubreuia** [comment] 2016-05-11 02:37
Hey @XXChester I'm working on bringing the plugin to all products right now, PhpStorm will soon be supported. I closed specific issues because they are duplicate with this one (I'll release it for all products at the same time).

**Comment by XXChester** [comment] 2016-05-11 12:27
👍  Awesome. I thought it was abandoned date, glad to hear it is not.

**Comment by sgeier** [comment] 2016-06-16 14:04
Glad to hear you are working on making it work on a variety of platforms. Is it possible to release a port as soon as its finished instead of waiting for release until all other platforms are done? This would help so much. I personally feel that my quality of codes degrades without SaveActions. I really want this on Android Studio.

**Comment by dubreuia** [comment] 2016-06-16 17:55
Is Android Studio a JetBrains product? I'm testing for:

- Intellij IDEA
- PhpStorm
- WebStorm
- PyCharm
- RubyMine
- AppCode
- CLion
- DataGrip (maybe?)

**Comment by dubreuia** [comment] 2016-06-16 18:02
The branch all-products works, I just haven't properly tested it yet

**Comment by sgeier** [comment] 2016-06-16 19:50
Dubreuia, Android Studio is based on Intellij IDEA. So practically the IDEA extension/plugins should work but it doesn't - in fact, and this is where the troubles com in, it cant even be downloaded as a plugin from the Plugin repository browser inside Android Studio. Its just not listed. I just verified this. Appears in Idea (version 15) but doesnt in Android Studio (lastest) 2.1.1. As its entirely based on Idea I would assume its not too much effort to enable it for Android Studio. Anyway I keep waiting :) Keep up the good work!

**Comment by krasa** [comment] 2016-06-17 02:05
You need to put `     <depends>com.intellij.modules.platform</depends>` into plugin.xml

**Comment by dubreuia** [comment] 2016-06-17 07:44
@krasa Thanks already done! The problem is that I have Java specific elements, so I need to split the plugin in two parts so it doesn't crash on startup with PyCharm, etc.

@sgeier OK it is not a JetBrains product but it should work too, note to self : https://developer.android.com/studio/index.html

I should release the all-product version this weekend if all goes well

**Comment by rmgrimm** [comment] 2016-08-01 22:15
@dubreuia Any update on the release of the all-product branch? We'd like to start using it across the dev team here as soon as it's ready

I'm happy to support in any testing as well, let me know. 👍

**Comment by dubreuia** [comment] 2016-08-04 16:56
Actually it's already ready, but I don't have time to test it so I didn't release it. I'll send you the jar so you can test if you want.

**Comment by dubreuia** [comment] 2016-08-04 17:09
[save-actions.zip](https://github.com/dubreuia/intellij-plugin-save-actions/files/402183/save-actions.zip)

Unzip, inside you have a .jar that you can import by hand in Intellij (Settings > Plugins > Import from jar). It is version 0.12-RC, it is based on 0.10 (not the latest available, you have probably on 0.11 right now).

**Comment by Tuupertunut** [comment] 2016-09-06 14:59
@dubreuia I can confirm that zipped version works on WebStorm 2016.2.3.

**Comment by manojvignesh** [comment] 2016-11-15 04:04
The zip file works fine in WebStorm 2016.2.4. Thanks for this awesome plugin.

**Comment by dubreuia** [comment] 2016-11-23 17:55
Thanks for your feedback, I'll make that available on the Jetbrains plugin repository.

**Comment by thiagotalma** [comment] 2016-12-21 22:14
Ok with PHPStorm!

**Comment by F21** [comment] 2016-12-24 04:56
Doesn't work with Gogland 1.0 EAP (163.10615.6) for golang. Would be awesome if it could be supported 😄

**Comment by spencero91** [comment] 2017-01-20 21:51
Any way we could get this added to the Jetbrains' plugin repository for PhpStorm?

**Comment by dubreuia** [comment] 2017-01-22 20:11
Hey @spencero91, try the save-actions zip I uploaded in this issue, you can import it directly in PhpStorm.

I don't want to upload it to the plugin repository just now, I haven't tested it in all products, and I don't have time to correct all the issues that are opened only for intellij...

The code is on branch master-all-product.

Keep me posted if that works for you

**Comment by dubreuia** [comment] 2017-02-10 21:41
Check #69 for licences to test in all products

**Comment by bentemple** [comment] 2017-03-30 22:44
For AS 2.3 I was able to download the latest version from https://plugins.jetbrains.com/plugin/7642-save-actions and then just install from within android studio:

**Android Studio (Menu) -> Preferences -> Plugins -> Install plugin from disk...**

Works just fine for me. The settings for it can be found under **Other Settings**

**Comment by dubreuia** [comment] 2017-04-05 16:48
Yeah it works as-is for Android Studio because it is a Java IDE. The other products will need the zip that is packaged in this issue.

**Comment by matthewadams** [comment] 2017-04-05 16:48
Just tested in WebStorm 2017.1. Appears to work.  Suggestions:
* Include an option to reformat when the editor autosaves.  The behavior I'm currently seeing is that reformatting is only taking place if I hit Ctrl-S/Cmd-S.
* Place language-specific configuration options in language-specific sections.  For example, "Organize Imports", "Rearrange fields ..." and "Compile File" only make sense for compiled languages (Java, TypeScript, etc), but they don't make any sense for JavaScript files.

Great plugin, especially for large teams!  👍

**Comment by dubreuia** [comment] 2017-04-05 17:02
Hey @matthewadams thanks for the testing and the tweet I appreciate it. 

> Include an option to reformat when the editor autosaves. The behavior I'm currently seeing is that reformatting is only taking place if I hit Ctrl-S/Cmd-S.

Actually, that should work. The autosave in Intellij is somewhat finicky, the easiest way to force it is by losing focus. Try (1) change a formatting or add unused import (2) click on another non-intellij window. It should reformat. That's the whole point of the plugin: not to think about it.

> Place language-specific configuration options in language-specific sections. For example, "Organize Imports", "Rearrange fields ..." and "Compile File" only make sense for compiled languages (Java, TypeScript, etc), but they don't make any sense for JavaScript files.

There is already a classification, the version you are using doesn't have the Java quick fixes. The one I left are, for me, available for all languages. It is based on the langage-based processors in the Intellij platform.

It is also very hard to classify language like this, for instance vanilla ES6 have imports but not the previous versions...

**Comment by matthewadams** [comment] 2017-04-05 17:56
Yes, it worked when WebStorm lost focus.  Maybe you should open an issue with JetBrains to get more consistent notification of autosave so that the behavior is consistent, but that's up to you.  Is there a more standard place from which to download the plugin than this issue now that it's been confirmed to work on other JetBrains products?  Thanks again!

**Comment by afwlehmann** [comment] 2017-06-13 04:55
Any chance getting a recent version of the plugin with the patch? I'm looking for support in pycharm and CLion. Sorry if I've overlooked something, but IMO the link provided above refers to a patched v11 of the plugin.

**Comment by dubreuia** [comment] 2017-06-22 08:52
Hey @afwlehmann I'll try to repackage it with a recent version of the plugin. Honestly, not much changed for non-Java languages in recent versions.

I won't release it on the official plugin repository, I don't have time to maintain the plugin for Intellij IDEA, if I support all product I'll have thousand of new users I don't have time to support

**Comment by afwlehmann** [comment] 2017-06-22 16:56
@dubreuia Thanks a lot!

**Comment by dubreuia** [comment] 2017-06-23 09:37
@afwlehmann I repackaged the plugin for all products on version 0.17. This time I merged the code to master, but didn't activate the plugin for all product (the line is commented in the plugin.xml file). It is not in the plugin repository yet but I might add it soon.

I tested in PyCharm and it seems to work. Keep me posted if it works for you.

[save-actions_0.17.jar.zip](https://github.com/dubreuia/intellij-plugin-save-actions/files/1097355/save-actions_0.17.jar.zip)

**Comment by dubreuia** [comment] 2017-06-23 09:47
Currently tested:

- PyCharm: OK
- AndroidStudio: OK (BUT exception quick fixes do not work, offending line META-INF/plugin.xml:73 do not load the java xml)

**Comment by afwlehmann** [comment] 2017-06-23 16:43
@dubreuia That's very much appreciated! I'll give it a try as soon as possible and let you know. Thanks :)

**Comment by afwlehmann** [comment] 2017-06-25 04:34
Works like a charm, thank you very much for your time and effort!

**Comment by dubreuia** [comment] 2017-06-27 12:35
Thanks @afwlehmann I'll slowly add supported products then. I'll add PyCharm for now

**Comment by celogeek** [comment] 2017-08-01 08:21
I can confirm it work as expected on the latest PyCharm on MacOS

**Comment by dubreuia** [comment] 2017-08-08 15:37
New version 0.18 should work in PyCharm and PhpStorm

**Comment by dubreuia** [comment] 2017-08-22 09:23
- AppCode (todo)
- CLion (todo)
- DataGrip (todo)
**- IntelliJ IDEA (OK)**
**- PhpStorm (OK)**
**- PyCharm (OK)**
- Rider (todo)
- RubyMine (todo)
- WebStorm (todo)

**Comment by dubreuia** [comment] 2017-09-05 11:54
Version 0.21 (https://github.com/dubreuia/intellij-plugin-save-actions/releases/tag/v0.21) adds official support to AndroidStudio. I'd like to do WebStorm after

- *IntelliJ IDEA (OK)*
- *PhpStorm (OK)*
- *PyCharm (OK)*
- *AndroidStudio (OK)*
- WebStorm (todo)
- Rider (todo)
- AppCode (todo)
- CLion (todo)
- DataGrip (todo)
- RubyMine (todo)

---

If you are using that plugin, could you rate it on https://plugins.jetbrains.com/plugin/7642-save-actions

**Comment by markiewb** [comment] 2017-09-29 19:32
@dubreuia: 0.21 works in 

WebStorm 2017.2.3
Build #WS-172.3968.27, built on August 29, 2017
JRE: 1.8.0_152-release-915-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

Except #110

**Comment by dubreuia** [comment] 2017-10-02 11:33
OK I'll correct #110 and add support for WebStorm when I have time

**Comment by studgeek** [comment] 2017-10-16 20:59
Is there a hurdle to just adding CLion also?

**Comment by dubreuia** [comment] 2017-10-22 12:35
Hey @studgeek I've given up on testing the plugin on all Jetbrain's products, I let users do that and report it here.

You can install the plugin in CLion by downloading the latest version from https://github.com/dubreuia/intellij-plugin-save-actions/releases and then doing "File > Settings > Plugins > Install plugin from disk" and choosing the jar you downloaded.

**Comment by dubreuia** [comment] 2017-10-26 11:11
Added WebStorm in https://github.com/dubreuia/intellij-plugin-save-actions/releases/tag/v0.23

- IntelliJ IDEA (OK)
- PhpStorm (OK)
- PyCharm (OK)
- AndroidStudio (OK)
- WebStorm (OK)
- Rider (todo)
- AppCode (todo)
- CLion (todo)
- DataGrip (todo)
- RubyMine (todo)

**Comment by d4rky-pl** [comment] 2017-12-06 12:26
Just tested and it seems to work fine in RubyMine :)
(too bad it's not the plugin I was looking for 😂)

**Comment by dubreuia** [comment] 2017-12-06 12:46
Hey @d4rky-pl, thank you for telling us! I hope you'll find what you are looking for :)

I'll add it to supported products next version

**Comment by dubreuia** [comment] 2018-01-09 15:10
Added RubyMine in https://github.com/dubreuia/intellij-plugin-save-actions/releases/tag/v0.25

-    IntelliJ IDEA (OK)
-    PhpStorm (OK)
-    PyCharm (OK)
-    AndroidStudio (OK)
-    WebStorm (OK)
-    RubyMine (OK)
-    Rider (todo)
-    AppCode (todo)
-    CLion (todo)
-    DataGrip (todo)

**Comment by dubreuia** [comment] 2018-01-27 12:58
It seems it works in CLion too (https://twitter.com/LlewellynFalco/status/957228926719463424). I'm adding support in next version https://github.com/dubreuia/intellij-plugin-save-actions/releases/tag/v0.26

**Comment by pablogarciamiranda** [comment] 2018-02-02 11:29
It's not working for me on WebStorm 2017.2.5

**Comment by dubreuia** [comment] 2018-02-02 13:14
Hey @pablogarciamiranda thanks for the update. I'll check it out.

**Comment by dubreuia** [comment] 2018-02-02 15:02
Hey @pablogarciamiranda thanks for the update. I'll just tested in "WebStorm 2017.3.4 Build #WS-173.4548.30, built on January 30, 2018" and it works. What is the problem?

**Comment by ptr1120** [comment] 2018-03-22 18:56
Rider support would be great since this plugin is very helpful.

**Comment by dubreuia** [comment] 2018-03-23 14:15
Hey @ptr1120, would you mind testing it? Download the jar at https://github.com/dubreuia/intellij-plugin-save-actions/releases/tag/v0.26, then "File > Settings > Plugins > Install plugin from disk..." and import the jar, restart and see if it works for you.

If it works, I'll add it to the supported products and you'll see it in "Browse Repository" in Intellij. Thanks.

**Comment by ptr1120** [comment] 2018-03-24 09:25
Thanks, @dubreuia, installed the plugin, plugin settings are available, but nothing happens during save action execution. The idea log says:

``` 
10:19:18.884 | INFO  | FileBasedIndexProjectHandler   | Reindexing refreshed files: 0 to update, calculated in 26ms
10:19:38.861 | DEBUG | SaveActionManager              | Running SaveActionManager on DocumentImpl[file://<myFolder>/MyFile.cs]
10:19:38.871 | DEBUG | SaveActionManager              | Running processors [RearrangeCode (true), OptimizeImports (true), ReformatAllText (true)], file RIDER_SOURCE_CODE_FILE, project Project '<myFolder>' NopCommerce
10:19:41.178 | INFO  | ProjectRootManagerComponent    | project roots have changed
10:19:42.140 | INFO  | PerformanceWatcher             | Pushing properties took 431ms; general responsiveness: ok; EDT responsiveness: 1/1 sluggish
10:19:42.280 | INFO  | PerformanceWatcher             | Indexable file iteration took 139ms; general responsiveness: ok; EDT responsiveness: ok
10:19:42.280 | INFO  | UnindexedFilesUpdater          | Unindexed files update started: 1 files to update
10:19:42.576 | INFO  | PerformanceWatcher             | Unindexed files update took 296ms; general responsiveness: ok; EDT responsiveness: ok
10:19:43.905 | INFO  | SolutionLifecycleHost          | Full warm solution load with caches took 34889 milliseconds.
10:19:47.571 | DEBUG | SaveActionManager              | Running SaveActionShortcutManager on com.intellij.openapi.actionSystem.AnActionEvent@7398727d
10:19:47.818 | DEBUG | SaveActionManager              | Running SaveActionShortcutManager on com.intellij.openapi.actionSystem.AnActionEvent@4c84eb97
10:19:47.988 | DEBUG | SaveActionManager              | Running SaveActionShortcutManager on com.intellij.openapi.actionSystem.AnActionEvent@6c8722f
10:19:48.138 | DEBUG | SaveActionManager              | Running SaveActionShortcutManager on com.intellij.openapi.actionSystem.AnActionEvent@15f1dda4
10:19:48.270 | DEBUG | SaveActionManager              | Running SaveActionShortcutManager on com.intellij.openapi.actionSystem.AnActionEvent@5f20dfe0
10:19:48.391 | DEBUG | SaveActionManager              | Running SaveActionShortcutManager on com.intellij.openapi.actionSystem.AnActionEvent@41a33d8e
10:19:48.512 | DEBUG | SaveActionManager              | Running SaveActionShortcutManager on com.intellij.openapi.actionSystem.AnActionEvent@5309b51
10:19:48.639 | DEBUG | SaveActionManager              | Running SaveActionShortcutManager on com.intellij.openapi.actionSystem.AnActionEvent@75104dcf
10:19:48.753 | DEBUG | SaveActionManager              | Running SaveActionShortcutManager on com.intellij.openapi.actionSystem.AnActionEvent@1aa13d13
10:19:48.894 | DEBUG | SaveActionManager              | Running SaveActionShortcutManager on com.intellij.openapi.actionSystem.AnActionEvent@111d84c5
10:21:55.025 | INFO  | ShowFilePathAction             | 
Exit code 1
` ` ` 

I obfuscated folder and filename, but the original values where correct.

**Comment by dubreuia** [comment] 2018-03-26 09:43
Thanks you for testing @ptr1120, I'll have to debug it. I'm updating:

- **IntelliJ IDEA (OK)**
- **PhpStorm (OK)**
- **PyCharm (OK)**
- **AndroidStudio (OK)**
- **WebStorm (OK)**
- **RubyMine (OK)**
- Rider (settings OK - reformat KO)
- AppCode (todo)
- CLion (todo)
- DataGrip (todo)

**Comment by qayshp** [comment] 2018-04-23 23:53
For me, using Rider on macOS, after downloading and pointing it at the jar, (unlike above) I don't get any errors in the Event Log, and I see the preference pane and it saves fine (like above).
Unfortunately it also seems not to change anything on save, regardless of the settings I enable.

**Comment by findpikachu** [comment] 2018-08-10 12:28
this plugin doen't work for clion.

**Comment by dubreuia** [comment] 2018-08-10 12:53
Ok I'll check Rider dans Clion before releasing 1.1.0, which should be by the end of the month

**Comment by dubreuia** [comment] 2018-08-13 15:45
CLion works. A bit too well since it deletes used imports but formatting is OK. See #180.

**Comment by dubreuia** [comment] 2018-08-14 10:00
Actually, Rider is not officially supported and CLion works so we're good for 1.1.0, no regression.

**Comment by bobvandevijver** [comment] 2018-08-27 14:47
I'm also looking forward to Rider support, but you say it's supported? How come?

**Comment by MartinX3** [comment] 2018-08-27 15:07
"ist not"
Maybe in 1.2.0?

**Comment by dubreuia** [comment] 2018-08-27 15:30
@bobvandevijver Rider is not supported because I don't have time to write the code. You can submit a PR to add Rider support anytime.

**Comment by bobvandevijver** [comment] 2018-08-27 16:01
Right. I mistakenly assumed you meant not supported from JetBrains, as you wrote "officially". I might take a look (although I've never touched JetBrains plugins before)

**Comment by dubreuia** [comment] 2018-08-27 16:09
Sorry for the mixup, I meant "If it is not in https://github.com/dubreuia/intellij-plugin-save-actions#compatibility, it might work but I haven't tested it"

Documentation on development environment setup: https://github.com/dubreuia/intellij-plugin-save-actions#contributing

**Comment by bobvandevijver** [comment] 2018-09-30 17:57
It seems that the plugin is doing it's job in Rider as you should expect, as it calls the `run` method of `com.intellij.codeInsight.actions.ReformatCodeProcessor`. The call itself simply doesn't do the formatting (it doesn't throw anything either), and I do not see anything weird during it's execution, so I'm stuck 😞

**Comment by dubreuia** [comment] 2018-10-01 15:19
@bobvandevijver Thank you for the debug. I'm pretty sure the reformat in Rider and PyCharm (maybe others) is not done by `ReformatCodeProcessor`. We'll need to provide specific implementation for those products (like `META-INF/plugin-java.xml` for Java), and call the proper formatter on save.

**Comment by bobvandevijver** [comment] 2018-10-01 21:16
I tried some more with the plugin, and it seems that the whole `CodeStyleManager` simply doesn't work in Rider. It has probably something to do with the backend connection with ReSharper, which is responsible for the formatting/optimizations.

I can trigger the reformat with the following, **ugly** hack:
```java
ActionManager.getInstance().getAction("ReformatCode")
    .actionPerformed(new AnActionEvent(null, DataManager.getInstance().getDataContext(),
        ActionPlaces.UNKNOWN, new Presentation(), ActionManager.getInstance(), 0));
```

This triggers the following logging in the frontend, which is the same when triggered from the menu/shortcut:
```
23:05:45.647 | INFO  | RiderActionOverride            | Executing ReSharper action 'RiderReformatCode'
23:05:45.647 | INFO  | RiderActionHandlers            | >> Begin backend 'RiderReformatCode' action session
23:05:45.649 | INFO  | RiderActionHandlers            | << End backend 'RiderReformatCode' action session
```

It does not play nice with any other action being executed simultaneously (such as "OptimizeImports"), so it is in no way an suitable solution.

So, it looks like the ReSharper action is simply not triggered/created when the `CodeStyleManager` is used. Do we really need to create a ReSharper plugin, which communicates with the frontend? (see https://www.jetbrains.com/help/resharper/sdk/Products/Rider.html). I cannot find really relevant documentation on this issue.

There are also some other issues when compiling the plugin with the Rider SDK, mostly missing classes, so I'm not sure if it's even possible to compile the current plugin for Rider. See https://github.com/bobvandevijver/intellij-plugin-save-actions/commit/0a1d0afd4a2984381e0016de3e0ebedb1dcd368d for the classes I needed to remove in order to being able to build for Rider.

(btw, if you want to open an another issue for this discussion just let me know)

**Comment by van800** [comment] 2018-10-02 07:49
@bobvandevijver 
I guess it should be something like:
` val actionId = ActionManager.getInstance().getAction(IdeActions.ACTION_EDITOR_REFORMAT) `
`
var component  =  project.getComponent<EditorImpl>().component
var dataContext = DataManager.getInstance().getDataContext(component)
`

`
fun executeAction(actionId: String, dataContext: DataContext) {
    frameworkLogger.info("Execute action: '$actionId'")
    val actionManager = ActionManagerEx.getInstanceEx()
    val action = actionManager.getAction(actionId)
    requireNotNull(action) { "action is null" }

    val event = AnActionEvent.createFromAnAction(action, null, "", dataContext)
    action.beforeActionPerformedUpdate(event)

    require(event.presentation.isEnabled) { "presentation.isEnabled is false for $actionId" }

    actionManager.fireBeforeActionPerformed(action, event.dataContext, event)
    action.actionPerformed(event)
    actionManager.fireAfterActionPerformed(action, event.dataContext, event)
}
`
I will ask colleagues about  calling reformat and OptimizeImports simultaneously.
I assume you are calling OptimizeImports with similar code above. 
Surprisingly "OptimizeImports" is not listed in IdeActions, so just hardcode it.

**Comment by van800** [comment] 2018-10-03 07:12
@bobvandevijver I have asked about multiple commands but no workaround for now. 
Not sure, what do you mean about vcs changed code. If you want to reformat everything in solution, you need to put solutionNode of SolutionExplorer to context like:

```
        val viewPane = SolutionExplorerViewPane.getInstance(project)
        val solutionNode = viewPane.model.root.children.filterIsInstance<SolutionExplorerModelNode>().single()

        val contextData = mapOf(
            Pair(PlatformDataKeys.SELECTED_ITEM.name, solutionNode),
            Pair(PlatformDataKeys.PROJECT.name, project),
            Pair(ProjectModelDataKeys.SOLUTION_VIEW.name, viewPane))

        var dataContext= SimpleDataContext.getSimpleContext(contextData, null)
```

**Comment by bobvandevijver** [comment] 2018-10-03 08:53
> Not sure, what do you mean about vcs changed code.

Reformat only changed lines (which is one of the options of the [`ReformatCodeProcessor`](https://github.com/dubreuia/intellij-plugin-save-actions/blob/master/src/main/java/com/dubreuia/processors/ReformatCodeProcessor.java#L19), which uses the `CodeStyleManager` internally)

**Comment by bobvandevijver** [comment] 2018-10-03 08:54
> Not sure, what do you mean about vcs changed code.

@van800 To reformat only changed lines according to your VCS (eg. git) (which is one of the options of the [`ReformatCodeProcessor`](https://github.com/dubreuia/intellij-plugin-save-actions/blob/master/src/main/java/com/dubreuia/processors/ReformatCodeProcessor.java#L19), which uses the `CodeStyleManager` internally)

**Comment by dubreuia** [comment] 2018-10-03 09:42
@van800 @bobvandevijver If you have an almost-working solution (or various possible solutions), could you post a PR with "WIP" prefix so we keep that code somewhere.

Also I'm creating an issue for Rider (see #198)

**Comment by hwangjr** [comment] 2018-10-16 15:34
Any plan to support GoLand IDE? It would be awesome to support GoLand IDE.

**Comment by dubreuia** [comment] 2018-11-15 20:14
Hey @hwangjr, would you mind downloading the latest jar in the release section (https://github.com/dubreuia/intellij-plugin-save-actions/releases/tag/v1.2.0) and test it in GoLang IDE. It might actually work. Can you report back on that? Thanks.

-    IntelliJ IDEA (OK)
-    PhpStorm (OK)
-    PyCharm (OK)
-    AndroidStudio (OK)
-    WebStorm (OK)
-    RubyMine (OK)
-    Rider (settings OK - reformat KO)
-    AppCode (todo)
-    CLion (todo)
-    DataGrip (todo)
-    GoLand IDE (todo)

**Comment by hwangjr** [comment] 2018-11-16 02:02
@dubreuia  yes, it works. Can you add to jetbrains plugin center? we can download from repositories directly.

**Comment by dubreuia** [comment] 2018-11-19 16:52
Ok @hwangjr I've added GoLand IDE to the list of compatible IDEs. You should uninstall the local plugin and reinstall it from the plugin repository so you get updates. Thanks! 


-    IntelliJ IDEA (OK)
-    PhpStorm (OK)
-    PyCharm (OK)
-    AndroidStudio (OK)
-    WebStorm (OK)
-    RubyMine (OK)
-    GoLand IDE (OK)
-    Rider (settings OK - reformat KO)
-    AppCode (todo)
-    CLion (todo)
-    DataGrip (todo)

**Comment by hwangjr** [comment] 2018-11-20 01:29
OK, Thanks.

**Comment by ned1988** [comment] 2019-04-29 10:32
is it possible to vote for AppCode? 😄 I would be also happy to test it

**Comment by hwangjr** [comment] 2019-04-29 14:55
> is it possible to vote for AppCode? 😄 I would be also happy to test it

you can test it then tell @dubreuia  the test result.

**Comment by ned1988** [comment] 2019-04-29 19:00
@hwangjr @dubreuia looks like it works fine in `AppCode 2019.1`, tomorrow will test it more

**Comment by ned1988** [comment] 2019-05-16 08:40
Found that some options are not available, I especially miss "No action if compile errors".
![Screenshot 2019-05-16 at 10 36 49](https://user-images.githubusercontent.com/1679724/57839419-f807c700-77c6-11e9-85de-4bbd993e62bc.png)

**Comment by bbakermmc** [comment] 2019-05-23 14:56
I looked for Save Actions in the marketplace and it doesnt exist?  Does this support rider?

![image](https://user-images.githubusercontent.com/30090055/58263034-54c82c00-7d49-11e9-8d26-20ecc09ca374.png)

**Comment by bobvandevijver** [comment] 2019-05-23 16:29
@bbakermmc I've created a plugin which "works" (is sometimes errors, only has the basic capabilities), which you can find here: https://github.com/dubreuia/intellij-plugin-save-actions/files/2449110/Save.Actions-0.0.1.zip. See https://github.com/dubreuia/intellij-plugin-save-actions/issues/198 for more information.

**Comment by dubreuia** [comment] 2019-06-03 15:16
@ned1988 Thanks for testing. The option "No action if compile errors" requires a compiler, and since it is platform specific (java, python, etc.) I haven't coded this already outside the Java ecosystem. There's a "core" plugin, used everywhere, and a "java" plugin, used for java products. We'll need "language" plugin for each product we want to fully support, Rider included. If it woks fine I'll mark it as supported then.

**Comment by dubreuia** [comment] 2019-10-17 08:57
I'm thinking of splitting this issue for each products, this issue is 4 years old...

**Comment by keyvchan** [comment] 2020-04-06 16:04
Any update?

**Comment by dubreuia** [comment] 2020-04-06 16:16
Hello @keyvchan ! I don't have time to work on this, but PRs are welcomed. Which product do you use?

**Comment by dubreuia** [comment] 2020-04-06 16:23
I've created 3 issues for each of Rider, AppCode and CLion. Can you guys go vote and post in the issues to see which is needed?

- Rider: #310 
- AppCode: #311 
- CLion: #312 

I'm closing this issue. Thanks

**Closed by dubreuia** 2020-04-06 16:23 UTC
Labels: enhancement
