### ISSUE TITLE
Redundant final modifier to try-with-resources conflicts with checkstyle

### ISSUE THREAD

**Issue by xunnanxu** [dubreuia/intellij-plugin-save-actions#229] opened 2019-03-09 02:59 UTC
**Describe the bug**
When "add final modifier to local variable" is enabled, `final` should not be added to try-with-resources block.

i.e.

```
try (InputStream is = ...) {

} catch (...)
```

not 

```
try (final InputStream is = ...) {

} catch (...)
```

This conflicts with checkstyle:
https://github.com/checkstyle/checkstyle/issues/3323

**To Reproduce**
Add a try catch block, the final modifier is added upon save.

**Expected behavior**
Final modifier should not be added in this case.

**Screenshots (optional)**
N/A

**Versions**
IntelliJ IDEA 2018.3.5 (Ultimate Edition)
Build #IU-183.5912.21, built on February 26, 2019
JRE: 1.8.0_152-release-1343-b28 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.2

**Attachments**
```
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="SaveActionSettings">
    <option name="actions">
      <set>
        <option value="activate" />
        <option value="noActionIfCompileErrors" />
        <option value="organizeImports" />
        <option value="reformatChangedCode" />
        <option value="fieldCanBeFinal" />
        <option value="localCanBeFinal" />
        <option value="missingOverrideAnnotation" />
        <option value="useBlocks" />
      </set>
    </option>
    <option name="configurationPath" value="" />
  </component>
</project>
```

**Comment by dubreuia** [comment] 2019-03-14 15:48
Thanks for posting @xunnanxu! But this is a duplicate of #168.

**Closed by dubreuia** 2019-03-14 15:48 UTC
