### ISSUE TITLE
Plugin settings reset after updating IDE

### ISSUE THREAD

**Issue by hwooo** [dubreuia/intellij-plugin-save-actions#239] opened 2019-04-18 16:47 UTC
**Describe the bug**
After updating IDE(IntelliJ, CLion) from 2018.3 to 2019.1, every setting has deleted.

**Versions**
Build #IU-191.6707.61 (IntelliJ is JBR 11)

**Comment by dubreuia** [comment] 2019-04-18 16:50
I haven't changed anything for 2019, but I know the settings api I'm using is getting deprecated. Might be the reason.

Can you send your idea.log file please?

**Comment by NDelt** [comment] 2019-04-18 16:55
Log is here https://gist.github.com/NDelt/956e81ebf7f9f83e5180d8eb0d53db5c

**Comment by dubreuia** [comment] 2019-04-19 11:08
I honestly don't know why it happens, I can't reproduce. I'll leave open but without more info I'll close it later.

**Comment by NDelt** [comment] 2019-04-19 11:55
What about OS? I'm using Windows 10 now. Isn' there any possibility that OS type will affect?

**Comment by dubreuia** [comment] 2019-12-13 09:33
Cannot reproduce, but another user had this recently

**Comment by dubreuia** [comment] 2020-09-11 22:12
Reopen if still an issue

**Closed by dubreuia** 2020-09-11 22:12 UTC
Labels: bug

**Comment by diegosouzapb** [comment] 2020-10-01 20:13
**Describe the bug:**
Whenever any plugin is updated, my entire Save Actions configuration is cleared.

**Versions:**
Save Actions: 2.2.0 set 16, 2020

IntelliJ IDEA 2020.2.2 (Ultimate Edition)
Build #IU-202.7319.50, built on September 14, 2020
Runtime version: 11.0.8+10-b944.31 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-48-generic
Current Desktop: ubuntu:GNOME
