### ISSUE TITLE
Reformat only changed code 

### ISSUE THREAD

**Issue by jiqimaogou** [dubreuia/intellij-plugin-save-actions#130] opened 2017-11-20 11:39 UTC
Reformat only changed code  somethings reformat the entire file.

**Comment by dubreuia** [comment] 2017-11-20 14:30
I need more info:

- Do you have a VCS configured in Intellij? (if not, the option will always reformat on whole file) 
- What version of intellij and the plugin are you using?
- What do you mean by "somethings"? Sometimes? What times exactly?

Thanks

**Comment by hosswald** [comment] 2017-12-18 13:34
Duplicate of #114.

**Comment by MicNeo** [comment] 2018-01-18 13:37
Hi,

I have same problem, I've checked option to format only code changed by me, but e.g. it adds final keywords to vars in methods I haven't touched. I use git, and it works as expected. Do I need setup VCS somehow special to get it working with this plugin?

My Intellij version: 2017.2.2, plugin: 0.25

**Closed** 2018-01-18 15:32 UTC
Labels: duplicate
