### ISSUE TITLE
auto scroll to the file first line when checked organize imports

### ISSUE THREAD

**Issue by funnyrabbit87** [dubreuia/intellij-plugin-save-actions#92] opened 2017-07-12 05:56 UTC
I found edit will auto scroll to the first line when  i checked organize imports after edit file. 
My intellij version is 2017.1.5, it will auto save changes. Anyone have same issue?

**Comment by dubreuia** [comment] 2017-07-12 08:19
I cannot reproduce @funnyrabbit87... what I did:

- Add unused import
- Scroll down
- Change window to force auto-save (triggers save-actions)
- It doesn't scroll back to first line

**Comment by funnyrabbit87** [comment] 2017-07-13 03:18
in my case(i tried again and again)
There is a import line in java file
import static com.pkg_name_is_long. classname .methodName
package name is very long

1.Checked organize imports, ReformateFile and Reformate Only Changed Code.
the import code will wrapped as below
import static com.pkg_name_is_long. classname 
                   .methodName
2.Scroll down
3.edit file write some code and wait 1 sec  for auto save
result is
scroll back to the import code position.

In my case the code is after "package ......"  so i said scroll back to 1st line.
It seems any edit will caused scroll back.

I hope save action don't auto wrap the import code. If i unchecked that 3 box. the code will NOT be wrapped. So i think it does not matter with the IDE.

I not sure if the root cause (scroll back) is imported by the plugin or the IDE. So please check. 
Hope you can reproduce.
Thanks

**Comment by markiewb** [comment] 2017-07-13 06:24
Can you please provide a sample file and a screencast (as gif) of the
issue!

Den 13 juli 2017 05:18 skrev "funnyrabbit87" <notifications@github.com>:

**Comment by dubreuia** [comment] 2017-07-13 12:20
Similar issue posted on stack https://stackoverflow.com/a/27706292/3253277

**Comment by Delfic** [comment] 2017-07-13 16:20
The problem is when the import is longer than the configured limit and you also have configured not to exceed the right margin.

This issue is already open for IDEA itself, thus, not being a save-actions issue
https://youtrack.jetbrains.com/issue/IDEA-161127

Vote for the issue, my team already did and if we vote more and more we can make them fix this :)

**Comment by dubreuia** [comment] 2017-07-13 18:47
Hey @Delfic thanks for the link on YouTrack. I voted on the issue and commented on it that it breaks my plugin. 

I'm keeping this issue open as long as the Intellij bug is not resolved.

**Comment by funnyrabbit87** [comment] 2017-07-14 05:25
@Delfic Thanks for your comment. I also voted.

**Comment by dubreuia** [comment] 2017-08-24 15:01
I'm doing some cleanup, closing this one for now since it is an intellij bug

**Closed by dubreuia** 2017-08-24 15:01 UTC
Labels: bug

**Comment by Delfic** [comment] 2017-08-24 15:24
Since I did what they suggested on https://youtrack.jetbrains.com/issue/IDEA-161127
Removing the "Ensure right margin is not exceeded! I have no such problem now. Our imports do exceed the right margin but that is not a problem for our team.
