### ISSUE TITLE
Failed plugin initialize 

### ISSUE THREAD

**Issue by szymek204** [dubreuia/intellij-plugin-save-actions#19] opened 2015-09-04 10:21 UTC
![pluginerror](https://cloud.githubusercontent.com/assets/14124484/9681568/4778c924-52ff-11e5-89c7-9fbc1ff96cac.PNG)

**Comment by dubreuia** [comment] 2015-09-07 12:56
Could you give me Intellij version / OS please? Did you install the plugin from the plugin management screen in Intellij ?

**Comment by dubreuia** [comment] 2016-02-08 19:50
Cannot reproduce / lack of information I'm closing the issue

**Closed by dubreuia** 2016-02-08 19:50 UTC
Labels: bug
