### ISSUE TITLE
Plugin adds unnecessary String concatenation

### ISSUE THREAD

**Issue by MALPI** [dubreuia/intellij-plugin-save-actions#56] opened 2016-08-05 12:44 UTC
Hi there,

we are experiencing the following Bug.
If you have a String like the following:

`"This is my very long test string this is split by formatter" +
                                  "Then save actions will break it"`

On Each time you save the file save actions will add an empty string:

`"This is my very long test string this is split by formatter" + ""+
                                  "Then save actions will break it"`

Next time you save the string will look like:
`"This is my very long test string this is split by formatter" + ""+ ""+
                                  "Then save actions will break it"`

And so on.. I am using Intellij 2016.2

**Comment by dubreuia** [comment] 2016-08-05 14:16
I can't reproduce... can you send me a full file where the problem exist, I tested it on that file:

    public class MacroProcessor {
        public static final String REF_PREFIX2 = "This is my very long test string this is split by formatter" +
                    "Then save actions will break it";
    }

And nothing happens. We have a lot of code like this in our codebase and I never saw any problem.

IntelliJ IDEA 2016.2.1
Build #IU-162.1447.26, built on August 2, 2016
JRE: 1.8.0_76-release-b216 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

But It was working with 2016.2 too

**Comment by krasa** [comment] 2016-08-05 14:27
https://youtrack.jetbrains.com/issue/IDEA-158493

**Comment by dubreuia** [comment] 2016-08-05 15:48
Thank you @krasa I'm closing the issue

**Closed by dubreuia** 2016-08-05 15:48 UTC

**Comment by MALPI** [comment] 2016-08-09 06:20
Sorry, my bad.
