### ISSUE TITLE
Save actions do not trigger on vim plugin save

### ISSUE THREAD

**Issue by jhzhang09** [dubreuia/intellij-plugin-save-actions#220] opened 2019-01-30 06:33 UTC
v1.2.0 work well, but 1.3.0 and 1.4.0 do not work.

IDEA version:
IntelliJ IDEA 2018.3.4 (Ultimate Edition)

**Comment by dubreuia** [comment] 2019-01-30 18:52
I though vim plugin never worked, see #28. Might be related with #222

**Comment by bborchard** [comment] 2019-03-08 22:36
On normal save ":w" it won't work because the plugin does not handle a single document save action (see #222).  
A workaround is to use ":wa" to save in the vim plugin.  This should trigger the 'Save All' action and thus the actions associated with this plugin

**Comment by dubreuia** [comment] 2019-03-14 15:42
Received by mail

> I am also using idea VIM with Intellij. I have save actions configured to optimize imports and reformat the file. However, my save actions configuration is not enacted when I save the file using the classic VIM saving keys ":w" + enter. My save actions configuration does work perfectly when I use Ctrl + S. 
> Do you know how to make save actions work with the classic VIM saving keys ":w"? 
> I have attached my Vim Emulation shortcut conflicts. 
> I have tried making Ctrl + S use VIM as the Handler, but that did not work. Any help would be appreciated. 

![vim_emulation_example](https://user-images.githubusercontent.com/657731/54370597-2ad2f900-4678-11e9-989b-511ae81f7f86.PNG)

**Comment by artus** [comment] 2019-03-20 10:09
> I have tried making Ctrl + S use VIM as the Handler, but that did not work. Any help would be appreciated.

This setting only chooses who should act upon a the capture of the CTRL+S shortcut:

- If the handler is the IDE, a regular "Save" will be executed.
- If the handler is VIM, the [appropriate vim command will be executed](http://vimdoc.sourceforge.net/htmldoc/windows.html#CTRL-W_CTRL-S).

Any update on this issue? Does anyone have an idea why this functionality stopped working?

**Comment by bborchard** [comment] 2019-03-20 13:04
Pretty sure it never worked - really this is a duplicate of #222 as that encapsulates the overarching issue.

**Comment by dubreuia** [comment] 2019-03-20 15:15
Yeah it's the same issue as #222

**Comment by dubreuia** [comment] 2019-03-23 22:29
Duplicates #222

**Closed by dubreuia** 2019-03-23 22:29 UTC
Labels: bug
