### ISSUE TITLE
couldn't find the plugin for Phpstorm 2017.2.1 

### ISSUE THREAD

**Issue by ishannz** [dubreuia/intellij-plugin-save-actions#95] opened 2017-08-02 22:16 UTC
I tried to install from the jar file as well, but I couldn't find the configuration for "Save actions"

**Comment by markiewb** [comment] 2017-08-03 06:23
Duplicate of #18.

Please use the "beta"-version for other non-Idea-IDEs, which is provided
there. You could be a tester for the Phpstorm part!

**Comment by dubreuia** [comment] 2017-08-03 08:12
Hey @ishannz, which jar file did you use? If it's the one from the Jetbrains plugin repository, it only works in Intellij IDEA and PyCharm for now.

Can you test this one: [save-actions_0.17.jar.zip](save-actions_0.17.jar.zip)? Thanks

**Comment by ishannz** [comment] 2017-08-03 10:55
Hey @dubreuia, thanks for the update, I used the latest(version 0.16) jar file from the https://plugins.jetbrains.com/plugin/7642-save-actions .    save-actions_0.17.jar.zip file not found! may be the wrong file path, I will test it and let you know once i got the jar.zip

**Comment by dubreuia** [comment] 2017-08-03 11:09
https://github.com/dubreuia/intellij-plugin-save-actions/files/1097355/save-actions_0.17.jar.zip

**Comment by ishannz** [comment] 2017-08-04 09:03
@dubreuia Thanks, mate, it works like a charm!

**Comment by dubreuia** [comment] 2017-08-04 10:04
Reopening the issue. 

Since it works, I'll re-upload the plugin in the plugin repository for PHPStorm.

**Comment by dubreuia** [comment] 2017-08-08 15:38
Version 0.18 from Jetbrains repo should work

**Closed by dubreuia** 2017-08-08 15:38 UTC
