### ISSUE TITLE
When working multi-window Android Studio, save actions plugin only works in the first instance.

### ISSUE THREAD

**Issue by GerritDeMeulder** [dubreuia/intellij-plugin-save-actions#134] opened 2017-11-29 16:02 UTC
It may be a luxury problem, 
but when you're working multi-project in Android Studio 3.0 (and thus also multi-window), 
i.e. opening a second project that has a demo in it, bit with bad code formatting, 
the save actions plug-in only works in the original project that was opened first.

If it's easily fixed, that would be great, like the plug-in already is;
if not, then it's maybe nice to know this limitation, hence the FYI.

**Comment by dubreuia** [comment] 2017-11-29 22:00
Actually, this was the very first issue opened (almost 3 years ago omg) and it should work properly. It got fixed in #1 than #13. 

It might be a Android Studio bug, because AFAIK it works in Intellij (I often have multiple windows opened too).

Can you post your idea.log please? Check https://github.com/dubreuia/intellij-plugin-save-actions#files-location

**Comment by GerritDeMeulder** [comment] 2017-11-30 10:21
Could it be drive related ? The reference projects are on another drive than my actual project. In any case, see log below (i have omitted project dirs for clarity).
It's working on the first opened project on D: drive, not on the one on C: drive. (tested with x=y spaces removal) 
Also FYI: there is a shortcut command to get to the idea logs in the menu help>show log in explorer> gets you to the directory (or is this windows only ?) .
```
2017-11-30 10:56:21,758 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Running SaveActionShortcutManager on com.intellij.openapi.actionSystem.AnActionEvent@6d3c4fbf 
2017-11-30 10:56:21,769 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Running processors [RearrangeCode (false), OptimizeImports (false), ReformatAllText (false), Compile (false)], file PsiJavaFile:ContractListFragment.java, project Project 'C:\[Project directory omitted]\EU4YouSingleActivity' EU4YouSingleActivity 
2017-11-30 10:56:21,771 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Using default storage 
2017-11-30 10:56:21,771 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Using default storage 
2017-11-30 10:56:21,771 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Using default storage 
2017-11-30 10:56:21,771 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Using default storage 
2017-11-30 10:56:21,771 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Using default storage 
2017-11-30 10:56:21,772 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Running processors [LocalCanBeFinal (false), UnqualifiedFieldAccess (false), FieldMayBeFinal (false), override (false), ControlFlowStatementWithoutBraces (false), Convert2Diamond (false), UnnecessaryThis (false), SuppressionAnnotation (false), FinalPrivateMethod (false), UnnecessarySemicolon (false), UnnecessaryFinalOnLocalVariableOrParameter (false)], file PsiJavaFile:ContractListFragment.java, project Project 'C:\[Project directory omitted]\EU4YouSingleActivity' EU4YouSingleActivity 
2017-11-30 10:56:45,960 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Running SaveActionShortcutManager on com.intellij.openapi.actionSystem.AnActionEvent@62bfc516 
2017-11-30 10:56:45,960 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Running processors [RearrangeCode (false), OptimizeImports (false), ReformatAllText (false), Compile (false)], file PsiJavaFile:ContractListFragment.java, project Project 'C:\[Project directory omitted]\EU4YouSingleActivity' EU4YouSingleActivity 
2017-11-30 10:56:45,960 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Using default storage 
2017-11-30 10:56:45,960 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Using default storage 
2017-11-30 10:56:45,960 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Using default storage 
2017-11-30 10:56:45,960 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Using default storage 
2017-11-30 10:56:45,960 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Using default storage 
2017-11-30 10:56:45,960 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Running processors [LocalCanBeFinal (false), UnqualifiedFieldAccess (false), FieldMayBeFinal (false), override (false), ControlFlowStatementWithoutBraces (false), Convert2Diamond (false), UnnecessaryThis (false), SuppressionAnnotation (false), FinalPrivateMethod (false), UnnecessarySemicolon (false), UnnecessaryFinalOnLocalVariableOrParameter (false)], file PsiJavaFile:ContractListFragment.java, project Project 'C:\[Project directory omitted]\EU4YouSingleActivity' EU4YouSingleActivity 
2017-11-30 10:58:46,011 [se-915-b01]   INFO - ide.actions.ShowFilePathAction - 
Exit code 1 
2017-11-30 11:02:26,740 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Running SaveActionShortcutManager on com.intellij.openapi.actionSystem.AnActionEvent@7f85e6f7 
2017-11-30 11:02:26,740 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Running processors [RearrangeCode (false), OptimizeImports (false), ReformatAllText (false), Compile (false)], file PsiJavaFile:ContractListFragment.java, project Project 'C:\[Project directory omitted]\EU4YouSingleActivity' EU4YouSingleActivity 
2017-11-30 11:02:26,740 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Using default storage 
2017-11-30 11:02:26,741 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Using default storage 
2017-11-30 11:02:26,741 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Using default storage 
2017-11-30 11:02:26,741 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Using default storage 
2017-11-30 11:02:26,741 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Using default storage 
2017-11-30 11:02:26,741 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Running processors [LocalCanBeFinal (false), UnqualifiedFieldAccess (false), FieldMayBeFinal (false), override (false), ControlFlowStatementWithoutBraces (false), Convert2Diamond (false), UnnecessaryThis (false), SuppressionAnnotation (false), FinalPrivateMethod (false), UnnecessarySemicolon (false), UnnecessaryFinalOnLocalVariableOrParameter (false)], file PsiJavaFile:ContractListFragment.java, project Project 'C:\[Project directory omitted]\EU4YouSingleActivity' EU4YouSingleActivity 
2017-11-30 11:04:17,042 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Running SaveActionShortcutManager on com.intellij.openapi.actionSystem.AnActionEvent@71f25f23 
2017-11-30 11:04:17,051 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Running processors [RearrangeCode (false), OptimizeImports (true), ReformatAllText (true), Compile (false)], file PsiJavaFile:MainActivity.java, project Project 'D:\[Project directory omitted]\ProjectTest' ProjectTest 
2017-11-30 11:04:17,069 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Using default storage 
2017-11-30 11:04:17,069 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Using default storage 
2017-11-30 11:04:17,069 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Using default storage 
2017-11-30 11:04:17,069 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Using default storage 
2017-11-30 11:04:17,069 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Using default storage 
2017-11-30 11:04:17,069 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Running processors [LocalCanBeFinal (false), UnqualifiedFieldAccess (false), FieldMayBeFinal (false), override (false), ControlFlowStatementWithoutBraces (false), Convert2Diamond (false), UnnecessaryThis (false), SuppressionAnnotation (false), FinalPrivateMethod (false), UnnecessarySemicolon (false), UnnecessaryFinalOnLocalVariableOrParameter (false)], file PsiJavaFile:MainActivity.java, project Project 'D:\[Project directory omitted]\ProjectTest' ProjectTest 
2017-11-30 11:04:21,314 [se-915-b01]   WARN - ConfigurableExtensionPointUtil - use other group instead of unexpected one: project.propCompiler 
2017-11-30 11:04:31,702 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Running SaveActionShortcutManager on com.intellij.openapi.actionSystem.AnActionEvent@31106c85 
2017-11-30 11:04:31,703 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Running processors [RearrangeCode (false), OptimizeImports (true), ReformatAllText (true), Compile (false)], file PsiJavaFile:MainActivity.java, project Project 'D:\[Project directory omitted]\ProjectTest' ProjectTest 
2017-11-30 11:04:31,705 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Using default storage 
2017-11-30 11:04:31,705 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Using default storage 
2017-11-30 11:04:31,706 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Using default storage 
2017-11-30 11:04:31,706 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Using default storage 
2017-11-30 11:04:31,706 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Using default storage 
2017-11-30 11:04:31,706 [se-915-b01]  DEBUG - ubreuia.core.SaveActionManager - Running processors [LocalCanBeFinal (false), UnqualifiedFieldAccess (false), FieldMayBeFinal (false), override (false), ControlFlowStatementWithoutBraces (false), Convert2Diamond (false), UnnecessaryThis (false), SuppressionAnnotation (false), FinalPrivateMethod (false), UnnecessarySemicolon (false), UnnecessaryFinalOnLocalVariableOrParameter (false)], file PsiJavaFile:MainActivity.java, project Project 'D:\[Project directory omitted]\ProjectTest' ProjectTest 

```

**Comment by dubreuia** [comment] 2017-11-30 12:06
Thanks for the shortcut in the "Help" menu I didn't know it.

I removed debug information last version, I don't have enough information. Your two projects are "ProjectTest" and "EU4YouSingleActivity" right? They both show in debug with proper configuration, I just don't know why the files don't get processed. 

I'll try to reproduce

**Comment by GerritDeMeulder** [comment] 2017-11-30 16:54
> Thanks for the shortcut in the "Help" menu I didn't know it.

Glad to be of help,
Yes, the two projects are "ProjectTest" and "EU4YouSingleActivity".

**Comment by dubreuia** [comment] 2019-01-17 22:39
Cannot reproduce, reopen if necessary

**Closed by dubreuia** 2019-01-17 22:39 UTC
Labels: bug, need more info
