### ISSUE TITLE
build.gradle editing with auto save on

### ISSUE THREAD

**Issue by wujek-srujek** [dubreuia/intellij-plugin-save-actions#14] opened 2015-07-03 18:58 UTC
When I edit a build.gradle file while the plugin is turned on, the code is formatted immediately as I type. This make it unusable. For example, I write:
println
and then press space, and the space is immediately removed.

This makes it pretty much impossible to code. As far as I know, this issue exist only on build.gradle files.

I'm using it in IDEA Ultimate 14.1.4.

**Comment by dubreuia** [comment] 2015-07-05 22:51
I'm going to check this out, but as a workaround, add your files to the ignore list:

Go to "File > Settings > Other Settings > Save Actions", then in the file path exclusion section, add a new exclusion for each build.gradle files. The format is described here: https://github.com/dubreuia/intellij-plugin-save-actions#file-path-exclusions

**Comment by wujek-srujek** [comment] 2015-07-07 07:53
Thanks for the tip.

**Comment by yissachar** [comment] 2015-09-24 21:44
I can confirm this issue. This was driving me crazy and I was about to turn off Save Actions entirely. Luckily, the file path exclusion workaround fixes it.

**Comment by fluidsonic** [comment] 2016-01-14 10:25
@dubreuia Using Path Exclusions doesn't solve the issue since they don't work at all.

No matter which of the following exclusions I add, I keep getting the popup "Organizing Imports…" after each keystroke:
- `.*/.*\.gradle`
- `.*/.*`
- `.*`

It only goes away when I completely disable Save Actions.

**Comment by yissachar** [comment] 2016-01-14 16:20
This is what I have in my file path exclusions and it works for me:

```
.*/.*\.gradle
.*\.gradle
```

I found I needed both in order to properly exclude both at the root level, as well as nested.

**Comment by dubreuia** [comment] 2016-02-08 19:48
@fluidsonic I added debug information in version 0.5 so we can check out why path exclusions do not work

**Comment by fluidsonic** [comment] 2016-02-09 10:05
Why isn't 0.5 available through the [plugin repository](https://plugins.jetbrains.com/plugin/7642)?

I installed the 0.5 jar file manually and the settings pane looks quite different now.
And the file path exclusions are finally working :)

Thanks!

**Comment by dubreuia** [comment] 2016-02-09 12:33
@fluidsonic Jetbrains has to validate it. Should be fast, like couple of days.

Happy to hear it works!

**Comment by dubreuia** [comment] 2016-05-25 18:18
#29 corrected I'm closing this one too

**Closed by dubreuia** 2016-05-25 18:18 UTC
Labels: bug
