### ISSUE TITLE
Save actions should be applied to only a subset of source files

### ISSUE THREAD

**Issue by stephanenicolas** [dubreuia/intellij-plugin-save-actions#8] opened 2015-03-31 17:27 UTC
For instance, I don't want to format my xml or gradle file (I just lost 30 minutes as the plugin had formatted a gradle properties files..).

So, it would be nice to add a feature to provide a list of file name masks to apply the save actions to.

Default : all
Alternative : apply file masks : 
the a field becomes enabled to enter a regexp list, comma separated like : *.java,*.xml

**Comment by dubreuia** [comment] 2015-04-02 17:01
Yeah I have the same problem. I started working on it already, the issue is this one: #3. I'm closing this issue as duplicates, but subscribe to #3 and you'll be notified of the new feature soon.

Thanks

**Closed** 2015-04-02 17:01 UTC
Labels: duplicate
