### ISSUE TITLE
NoSuchMethodError: com.intellij.codeInsight.actions.RearrangeCodeProcessor

### ISSUE THREAD

**Issue by stevewheeler** [dubreuia/intellij-plugin-save-actions#103] opened 2017-09-01 23:43 UTC
In my IntelliJ IDE, I just updated to the latest Save Actions plugin, and the auto-formatting on save stopped working.

The instructions in this thread didn't fix the problem as I do not have the Rearrange options checked:

https://github.com/dubreuia/intellij-plugin-save-actions/issues/7

I only have "Activate save actions", "Organize imports", "Reformat file", and "Reformat only changed code" checked.

Here is the stack trace:

com.intellij.codeInsight.actions.RearrangeCodeProcessor.<init>(Lcom/intellij/openapi/project/Project;[Lcom/intellij/psi/PsiFile;Ljava/lang/String;Ljava/lang/Runnable;Z)V
java.lang.NoSuchMethodError: com.intellij.codeInsight.actions.RearrangeCodeProcessor.<init>(Lcom/intellij/openapi/project/Project;[Lcom/intellij/psi/PsiFile;Ljava/lang/String;Ljava/lang/Runnable;Z)V
	at com.dubreuia.processors.RearrangeCodeProcessor.<init>(RearrangeCodeProcessor.java:37)
	at com.dubreuia.processors.ProcessorFactory.getSaveActionsProcessors(ProcessorFactory.java:21)
	at com.dubreuia.core.SaveActionManager.getSaveActionsProcessors(SaveActionManager.java:126)
	at com.dubreuia.core.SaveActionManager.processPsiFile(SaveActionManager.java:97)
	at com.dubreuia.core.SaveActionManager.beforeDocumentSaving(SaveActionManager.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:437)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:398)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:387)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:373)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:44)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:230)
	at com.sun.proxy.$Proxy21.beforeDocumentSaving(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.multiCast(FileDocumentManagerImpl.java:153)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.lambda$new$0(FileDocumentManagerImpl.java:132)
	at com.sun.proxy.$Proxy21.beforeDocumentSaving(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.lambda$doSaveDocumentInWriteAction$4(FileDocumentManagerImpl.java:418)
	at com.intellij.pom.core.impl.PomModelImpl.guardPsiModificationsIn(PomModelImpl.java:411)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.doSaveDocumentInWriteAction(FileDocumentManagerImpl.java:417)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.lambda$doSaveDocument$2(FileDocumentManagerImpl.java:390)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:91)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.doSaveDocument(FileDocumentManagerImpl.java:390)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:312)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:290)
	at com.intellij.openapi.application.impl.ApplicationImpl.saveAll(ApplicationImpl.java:1442)
	at com.intellij.ide.actions.SaveAllAction.actionPerformed(SaveAllAction.java:36)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:215)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:232)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:570)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:619)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:618)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:633)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

My IDE:

IntelliJ IDEA 2017.1.5
Build #IC-171.4694.70, built on July 4, 2017
JRE: 1.8.0_112-release-736-b21 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-92-generic

**Comment by markiewb** [comment] 2017-09-02 08:29
@Steve I cannot reproduce it using

IntelliJ IDEA 2017.2.3
Build #IC-172.3968.16, built on August 22, 2017
JRE: 1.8.0_152-release-915-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

Perhaps the code, which is used in com.dubreuia.processors.RearrangeCodeProcessor, uses API which has been changed from 2017.1.x to 2017.2.x. This plugin (I guess so) is developed/tested against 2017.2.x

**Comment by dubreuia** [comment] 2017-09-04 09:29
The constructor I'm using in 0.20 is the one added by this commit https://github.com/JetBrains/intellij-community/commit/10d97920c99352fee9cf03cbf1185771c4c56dfd and you don't seem to have it. I should't be using it since it is really recent (I try to have 1 year of backwards compatibility).

I think I got mixed up in the latest release with the SDK I used, I though I was building with (162.1447.26 2016-08-02 02:23:04 MSK https://www.jetbrains.com/intellij-repository/releases), but I think I build with something more recent.

You have 2 choices: you either wait I correct the issue, or you update you IDE.

**Comment by dubreuia** [comment] 2017-09-05 11:46
Fixed in master I'll release the plugin later today

**Comment by dubreuia** [comment] 2017-09-05 16:26
Fixed
---
If you are using that plugin, rate it on https://plugins.jetbrains.com/plugin/7642-save-actions

**Closed by dubreuia** 2017-09-05 16:26 UTC
Labels: bug

**Comment by stevewheeler** [comment] 2017-09-05 18:42
The fix worked great when I updated to version 0.21 of the plugin. Thanks for fixing this so quickly!
